apiVersion: v1
kind: ConfigMap
metadata:
  namespace: aromathek-gateway
  name: gateway-config
  labels:
    app: gateway
data:
  PORT: "8080"
  DB_HOST: "mariadb.default.svc.cluster.local" # ggf. Namespace/Service-Namen anpassen
  DB_NAME: "parfumsammlung_gateway"
  PFSENSE_HOST: "<pfsense-ip>"
  PFSENSE_CERT_PATH: "/conf/acme/Gateway-Cert.fullchain"
  PFSENSE_KEY_PATH: "/conf/acme/Gateway-Cert.key"
